### ISSUE TITLE
Missing nerd font dependancy?

### ISSUE THREAD

**Issue by OptimoSupreme** [NotAShelf/microfetch#13]
i ran this with `nix-shell -p microfetch` and this is the output I get. I am new to nix, so my gut reaction is that it was a missing font dependency. But at the same time I kind of thought point of nix was to fix dependency issues. This could just be me being dumb.

![image](https://github.com/user-attachments/assets/6c1c4a57-af57-4df9-8251-c89323c28189)

**Comment by NotAShelf** [comment]
It's not missing per-se: Nerdfonts is not something I can provide out of the box since fonts are a personal thing, and more importantly you will need a terminal emulator that uses the font I may choose to use.

The solution is quite simple: Configure your terminal emulator to use a nerdfonts patched font.

**Comment by OptimoSupreme** [comment]
This makes so much sense, thanks for the explanation!

**Comment by NotAShelf** [comment]
Happy to help, enjoy Microfetch :)
